### ISSUE TITLE
Error: Response validation failed: invalid content type (text/plain).  These are valid: application/json

### ISSUE THREAD

**Issue by am17torres** [swagger-api/swagger-node#266]
I created a new project using `swagger project create hello-world`. 

No Problems hitting it with curl
```bash
$ curl http://127.0.0.1:10010/hello?name=Scott
"Hello, Scott!"
$ curl http://127.0.0.1:10010/hello?name=Scott
"Hello, Scott!"
$ curl http://127.0.0.1:10010/hello?name=Scott
"Hello, Scott!"
```

Now, if you try hitting it in a browser,
The first time the page renders "Hello, Scott!" as expected. 

The second time however,
```
Error: Response validation failed: invalid content type (text/plain).  These are valid: application/json
   at Object.validateContentType (/Users/antorres/code/scratch/hello-world/node_modules/swagger-express-mw/node_modules/swagger-node-runner/node_modules/swagger-tools/lib/validators.js:212:11)
   at ServerResponse.end (/Users/antorres/code/scratch/hello-world/node_modules/swagger-express-mw/node_modules/swagger-node-runner/node_modules/swagger-tools/middleware/swagger-validator.js:188:20)
   at ServerResponse.send (/Users/antorres/code/scratch/hello-world/node_modules/express/lib/response.js:204:10)
   at ServerResponse.json (/Users/antorres/code/scratch/hello-world/node_modules/express/lib/response.js:249:15)
   at hello (/Users/antorres/code/scratch/hello-world/api/controllers/hello_world.js:43:7)
   at swaggerRouter (/Users/antorres/code/scratch/hello-world/node_modules/swagger-express-mw/node_modules/swagger-node-runner/node_modules/swagger-tools/middleware/swagger-router.js:396:20)
   at Layer.handle [as handle_request] (/Users/antorres/code/scratch/hello-world/node_modules/express/lib/router/layer.js:95:5)
   at trim_prefix (/Users/antorres/code/scratch/hello-world/node_modules/express/lib/router/index.js:312:13)
   at /Users/antorres/code/scratch/hello-world/node_modules/express/lib/router/index.js:280:7
   at Function.process_params (/Users/antorres/code/scratch/hello-world/node_modules/express/lib/router/index.js:330:12)
```

I've tracked it down to the following lines of code in `express/lib/response.js`
```javascript
  // freshness
  if (req.fresh) this.statusCode = 304;

  // strip irrelevant headers
  if (204 == this.statusCode || 304 == this.statusCode) {
    this.removeHeader('Content-Type');
    this.removeHeader('Content-Length');
    this.removeHeader('Transfer-Encoding');
    chunk = '';
  }
```
causing `validateContentType` in `swagger-tools/lib/validators.js` to fail. This is as far as I was able to trace it back, I'm not sure what sets req.fresh to be set to true. 

Hope this helps track the problem down.

**Comment by whitlockjc** [comment]
There are two things going on:

1. Something is causing an error to be unhandled
2. All unhandled errors will trigger the [default error handling](http://www.senchalabs.org/connect/errorHandler.html) in Connect/Express/... which is sending a `Content-Type` that does not match what your Swagger document says it produces

To identify the first issue, I'd recommend starting your project using `DEBUG=swagger-tools* swagger project start` to see what error is being thrown, and by whom, so you can see what the real root issue is.  To fix the second issue, you need to add an error handler to your application as documented here: http://www.senchalabs.org/connect/errorHandler.html

**Comment by am17torres** [comment]
Keep in mind, this is a vanilla project, I haven't changed any lines of code and I'm using Express.

When I comment this code, the problem goes away:
```javascript
  // freshness
  // if (req.fresh) this.statusCode = 304;
```


Here is the output of the debugger when requesting the page in a browser **Note the refresh**
```bash
$ DEBUG=swagger-tools* swagger project start
  swagger-tools:middleware:metadata GET /hello +3s
  swagger-tools:middleware:metadata   Is a Swagger path: true +1ms
  swagger-tools:middleware:metadata   Is a Swagger operation: true +0ms
  swagger-tools:middleware:metadata   Processing Parameters +0ms
  swagger-tools:middleware:metadata     name +0ms
  swagger-tools:middleware:metadata       Type: string +0ms
  swagger-tools:middleware:metadata       Value provided: false +0ms
  swagger-tools:middleware:metadata       Value: undefined +0ms
  swagger-tools:middleware:security GET /hello +0ms
  swagger-tools:middleware:security   Will process: yes +0ms
  swagger-tools:middleware:validator GET /hello +0ms
  swagger-tools:middleware:validator   Will process: yes +0ms
  swagger-tools:middleware:validator   Request validation: succeeded +0ms
  swagger-tools:middleware:router GET /hello +0ms
  swagger-tools:middleware:router   Will process: yes +0ms
  swagger-tools:middleware:router   Route handler: hello_world_hello +0ms
  swagger-tools:middleware:router   Mock mode: false +0ms
  swagger-tools:middleware:validator   Response validation: succeeded +1ms


 # refresh browser


  swagger-tools:middleware:metadata GET /hello +7s
  swagger-tools:middleware:metadata   Is a Swagger path: true +0ms
  swagger-tools:middleware:metadata   Is a Swagger operation: true +0ms
  swagger-tools:middleware:metadata   Processing Parameters +0ms
  swagger-tools:middleware:metadata     name +0ms
  swagger-tools:middleware:metadata       Type: string +0ms
  swagger-tools:middleware:metadata       Value provided: false +0ms
  swagger-tools:middleware:metadata       Value: undefined +0ms
  swagger-tools:middleware:security GET /hello +0ms
  swagger-tools:middleware:security   Will process: yes +0ms
  swagger-tools:middleware:validator GET /hello +0ms
  swagger-tools:middleware:validator   Will process: yes +1ms
  swagger-tools:middleware:validator   Request validation: succeeded +0ms
  swagger-tools:middleware:router GET /hello +0ms
  swagger-tools:middleware:router   Will process: yes +0ms
  swagger-tools:middleware:router   Route handler: hello_world_hello +0ms
  swagger-tools:middleware:router   Mock mode: false +0ms
  swagger-tools:middleware:validator   Response validation: failed +0ms
  swagger-tools:middleware:validator   Reason: Invalid content type (text/plain).  These are valid: application/json +0ms
  swagger-tools:middleware:validator   Stack: +1ms
  swagger-tools:middleware:validator       at Object.validateContentType (~/hello-world/node_modules/swagger-express-mw/node_modules/swagger-node-runner/node_modules/swagger-tools/lib/validators.js:212:11) +0ms
  swagger-tools:middleware:validator       at ServerResponse.end (~/hello-world/node_modules/swagger-express-mw/node_modules/swagger-node-runner/node_modules/swagger-tools/middleware/swagger-validator.js:188:20) +0ms
  swagger-tools:middleware:validator       at ServerResponse.send (~/hello-world/node_modules/express/lib/response.js:204:10) +0ms
  swagger-tools:middleware:validator       at ServerResponse.json (~/hello-world/node_modules/express/lib/response.js:249:15) +0ms
  swagger-tools:middleware:validator       at hello (~/hello-world/api/controllers/hello_world.js:43:7) +0ms
  swagger-tools:middleware:validator       at swaggerRouter (~/hello-world/node_modules/swagger-express-mw/node_modules/swagger-node-runner/node_modules/swagger-tools/middleware/swagger-router.js:396:20) +0ms
  swagger-tools:middleware:validator       at Layer.handle [as handle_request] (~/hello-world/node_modules/express/lib/router/layer.js:95:5) +0ms
  swagger-tools:middleware:validator       at trim_prefix (~/hello-world/node_modules/express/lib/router/index.js:312:13) +0ms
  swagger-tools:middleware:validator       at ~/hello-world/node_modules/express/lib/router/index.js:280:7 +0ms
  swagger-tools:middleware:validator       at Function.process_params (~/hello-world/node_modules/express/lib/router/index.js:330:12) +0ms
Error: Response validation failed: invalid content type (text/plain).  These are valid: application/json
    at Object.validateContentType (~/hello-world/node_modules/swagger-express-mw/node_modules/swagger-node-runner/node_modules/swagger-tools/lib/validators.js:212:11)
    at ServerResponse.end (~/hello-world/node_modules/swagger-express-mw/node_modules/swagger-node-runner/node_modules/swagger-tools/middleware/swagger-validator.js:188:20)
    at ServerResponse.send (~/hello-world/node_modules/express/lib/response.js:204:10)
    at ServerResponse.json (~/hello-world/node_modules/express/lib/response.js:249:15)
    at hello (~/hello-world/api/controllers/hello_world.js:43:7)
    at swaggerRouter (~/hello-world/node_modules/swagger-express-mw/node_modules/swagger-node-runner/node_modules/swagger-tools/middleware/swagger-router.js:396:20)
    at Layer.handle [as handle_request] (~/hello-world/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (~/hello-world/node_modules/express/lib/router/index.js:312:13)
    at ~/hello-world/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (~/hello-world/node_modules/express/lib/router/index.js:330:12)
```

I'm curious if this is a versioning issue, here is my node modules
```bash
$ npm list | grep -i -e swagger -e express
├─┬ express@4.13.3
└─┬ swagger-express-mw@0.0.4
  └─┬ swagger-node-runner@0.4.5
    └─┬ swagger-tools@0.9.0
      ├─┬ swagger-converter@0.1.7
```

**Comment by oliverhr** [comment]
This work for me:
https://github.com/apigee-127/swagger-tools/issues/108#issuecomment-121734617

```
SwaggerExpress.create(config, function(err, swaggerExpress) {
  if (err) { throw err; }

  // install all the swagger middleware
  swaggerExpress.register(app);

  // Custom error handler that returns JSON
  app.use(function(err, req, res, next) {
    if (typeof err !== 'object') {
      // If the object is not an Error, create a representation that appears to be
      err = {
        message: String(err) // Coerce to string
      };
    } else {
      // Ensure that err.message is enumerable (It is not by default)
      Object.defineProperty(err, 'message', { enumerable: true });
    }
    res.statusCode = res.statusCode || 500;
    res.json(err);
  });

  var port = process.env.PORT || 10123;
  app.listen(port);
});
```

**Comment by theganyo** [comment]
@am17torres Thanks for your report. It looks like there's an issue with swagger-tools handling the 304 coming from express. I'm investigating.

**Comment by am17torres** [comment]
That works for me too, not sure why the presence of that makes a difference. 

@theganyo good to hear. I was just about to post that because if you do a `cmd+shift+r` to reload in the browser, even without @oliverhr custom error handler, there is no longer an error.

**Comment by theganyo** [comment]
A new swagger-tools will released imminently that will address the 304 issue when using Express. In the meantime, I've updated swagger-node-runner to address the issue of not registering the error handler. Specifically: If you had `mapErrorsToJson: true` in the `swagger` section of your config file, it should have been adding an appropriate error handler to ensure errors would be delivered to the client in JSON format. This operates similarly to the error handler mentioned by oliverhr above. You should no longer need to include this kind of handler if that property is in your config.

**Comment by whitlockjc** [comment]
This has been fixed in swagger-tools: https://github.com/apigee-127/swagger-tools/blob/master/RELEASE_NOTES.md#v091-2015-08-04

**Comment by am17torres** [comment]
Everything seems to be working now. Thanks!

**Comment by diaspar** [comment]
@am17torres @theganyo I still having this issue. One request returns the expected output and the next request gives me this error:

Error: Response validation failed: invalid content type (text/plain).  These are valid: application/json

I uninstalled swagger and then I globally installed it again. I can see that swagger tools is updated:

```
└── swagger-tools@0.9.2 (parseurl@1.3.0, path-to-regexp@1.2.0, qs@4.0.0, traverse@0.6.6, string@3.3.1, spark-md5@1.0.0, body-parser@1.13.3, superagent@1.3.0, json-refs@0.3.2, multer@0.1.8, swagger-converter@0.1.7, lodash-compat@3.10.1, z-
schema@3.12.2)
```
Is there something else I should do?

**Comment by theganyo** [comment]
Try deleting node_modules in your app and doing a new `npm install`.

**Comment by diaspar** [comment]
@theganyo worked!!! thanks.

Curiosity, why it worked if swagger-node (and the tools) are global?

**Comment by theganyo** [comment]
Awesome! 

Why? Well, yes, the swagger-node CLI is installed globally... but the runtime components are directly part of your application - so it's self-contained.
